package com.stellae.app.ui.screens.boss

import androidx.compose.animation.AnimatedContent
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.core.FastOutSlowInEasing
import androidx.compose.animation.core.RepeatMode
import androidx.compose.animation.core.animateFloat
import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.infiniteRepeatable
import androidx.compose.animation.core.rememberInfiniteTransition
import androidx.compose.animation.core.tween
import androidx.compose.animation.fadeIn
import androidx.compose.animation.fadeOut
import androidx.compose.animation.scaleIn
import androidx.compose.animation.scaleOut
import androidx.compose.animation.togetherWith
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Shield
import androidx.compose.material.icons.filled.Timer
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.draw.scale
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.stellae.app.domain.gamification.BossChallenge
import com.stellae.app.ui.components.PrimaryButton
import com.stellae.app.ui.components.QuizOption
import com.stellae.app.ui.components.QuizOptionState
import com.stellae.app.ui.components.SecondaryButton
import com.stellae.app.ui.components.StarfieldBackground
import com.stellae.app.ui.components.XpProgressBar
import com.stellae.app.ui.theme.BgCard
import com.stellae.app.ui.theme.BgDeep
import com.stellae.app.ui.theme.BgElevated
import com.stellae.app.ui.theme.BgSurface
import com.stellae.app.ui.theme.BorderGlow
import com.stellae.app.ui.theme.BorderSubtle
import com.stellae.app.ui.theme.Correct
import com.stellae.app.ui.theme.Gold
import com.stellae.app.ui.theme.GoldBright
import com.stellae.app.ui.theme.GoldDim
import com.stellae.app.ui.theme.StellaeShapes
import com.stellae.app.ui.theme.StellaeTypography
import com.stellae.app.ui.theme.TextMuted
import com.stellae.app.ui.theme.TextPrimary
import com.stellae.app.ui.theme.TextSecondary
import com.stellae.app.ui.theme.Wrong
import kotlinx.coroutines.delay

// ── Sample boss questions ─────────────────────────────────────────────────────
// In production these would be generated by GetNextQuestionUseCase filtered by dignityTypes

private data class BossQuestion(
    val text: String,
    val options: List<String>,
    val correctIndex: Int
)

private val DOMICILE_BOSS_QUESTIONS = listOf(
    BossQuestion("Which sign is the Sun's domicile?", listOf("Leo", "Aries", "Sagittarius", "Cancer"), 0),
    BossQuestion("Which sign is the Moon's domicile?", listOf("Cancer", "Taurus", "Virgo", "Pisces"), 0),
    BossQuestion("Mercury rules which two signs?", listOf("Gemini & Virgo", "Aries & Scorpio", "Leo & Cancer", "Libra & Pisces"), 0),
    BossQuestion("Venus rules which two signs?", listOf("Taurus & Libra", "Gemini & Virgo", "Aries & Scorpio", "Leo & Aquarius"), 0),
    BossQuestion("Mars rules which two signs?", listOf("Aries & Scorpio", "Leo & Aquarius", "Taurus & Libra", "Gemini & Virgo"), 0),
    BossQuestion("Jupiter rules which two signs?", listOf("Sagittarius & Pisces", "Aries & Scorpio", "Leo & Aquarius", "Cancer & Capricorn"), 0),
    BossQuestion("Saturn rules which two signs?", listOf("Capricorn & Aquarius", "Taurus & Libra", "Aries & Scorpio", "Cancer & Leo"), 0),
    BossQuestion("What is the domicile ruler of Aries?", listOf("Mars", "Sun", "Jupiter", "Venus"), 0),
    BossQuestion("What is the domicile ruler of Libra?", listOf("Venus", "Moon", "Saturn", "Jupiter"), 0),
    BossQuestion("What is the domicile ruler of Pisces?", listOf("Jupiter", "Venus", "Moon", "Mars"), 0),
    BossQuestion("What is the domicile ruler of Taurus?", listOf("Venus", "Mercury", "Moon", "Saturn"), 0),
    BossQuestion("What is the domicile ruler of Scorpio?", listOf("Mars", "Pluto", "Jupiter", "Saturn"), 0),
    BossQuestion("What is the domicile ruler of Capricorn?", listOf("Saturn", "Mars", "Jupiter", "Venus"), 0),
    BossQuestion("What is the domicile ruler of Aquarius?", listOf("Saturn", "Uranus", "Jupiter", "Mercury"), 0)
)

private val EXALTATION_BOSS_QUESTIONS = listOf(
    BossQuestion("The Sun is exalted at 19° of which sign?", listOf("Aries", "Leo", "Taurus", "Sagittarius"), 0),
    BossQuestion("The Moon is exalted at 3° of which sign?", listOf("Taurus", "Cancer", "Pisces", "Virgo"), 0),
    BossQuestion("Mercury is exalted in which sign?", listOf("Virgo", "Gemini", "Capricorn", "Libra"), 0),
    BossQuestion("Venus is exalted at 27° of which sign?", listOf("Pisces", "Taurus", "Libra", "Gemini"), 0),
    BossQuestion("Mars is exalted at 28° of which sign?", listOf("Capricorn", "Aries", "Scorpio", "Taurus"), 0),
    BossQuestion("Jupiter is exalted at 15° of which sign?", listOf("Cancer", "Sagittarius", "Pisces", "Leo"), 0),
    BossQuestion("Saturn is exalted at 21° of which sign?", listOf("Libra", "Capricorn", "Aquarius", "Aries"), 0)
)

private fun getBossQuestions(boss: BossChallenge): List<BossQuestion> {
    return when {
        "domicile" in boss.dignityTypes -> DOMICILE_BOSS_QUESTIONS
        "exaltation" in boss.dignityTypes -> EXALTATION_BOSS_QUESTIONS
        else -> (DOMICILE_BOSS_QUESTIONS + EXALTATION_BOSS_QUESTIONS).shuffled()
    }.take(boss.questionCount)
}

// ── Phase enum ────────────────────────────────────────────────────────────────

private enum class BossPhase { INTRO, CHALLENGE, VICTORY, DEFEAT }

// ── BossScreen ────────────────────────────────────────────────────────────────

/**
 * Boss challenge screen. Loads the challenge by [bossId] from BossChallenge.ALL,
 * presents the quiz, then shows a victory or defeat result.
 *
 * Usage:
 *   BossScreen(
 *       bossId = "domicile_boss",
 *       onBack = { navController.popBackStack() }
 *   )
 */
@Composable
fun BossScreen(
    bossId: String,
    onBack: () -> Unit,
    modifier: Modifier = Modifier
) {
    val boss = remember(bossId) { BossChallenge.findById(bossId) }

    if (boss == null) {
        // Fallback for unknown boss ID
        Box(
            contentAlignment = Alignment.Center,
            modifier = modifier
                .fillMaxSize()
                .background(BgDeep)
        ) {
            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                Text(
                    text = "Challenge not found",
                    style = StellaeTypography.bodyLg.copy(color = TextSecondary)
                )
                Spacer(modifier = Modifier.height(16.dp))
                SecondaryButton(text = "Go Back", onClick = onBack)
            }
        }
        return
    }

    val questions = remember(boss) { getBossQuestions(boss) }
    var phase by remember { mutableStateOf(BossPhase.INTRO) }
    var currentIndex by remember { mutableIntStateOf(0) }
    var selectedOption by remember { mutableStateOf<Int?>(null) }
    var isAnswerRevealed by remember { mutableStateOf(false) }
    val answeredCorrectly = remember { mutableStateListOf<Boolean>() }
    var remainingSeconds by remember { mutableIntStateOf(boss.timeLimitSeconds ?: 0) }
    var timerActive by remember { mutableStateOf(false) }

    // Countdown timer
    LaunchedEffect(timerActive) {
        if (timerActive && boss.timeLimitSeconds != null) {
            while (remainingSeconds > 0 && timerActive) {
                delay(1000L)
                remainingSeconds--
            }
            if (remainingSeconds == 0 && timerActive) {
                // Time's up — determine pass/fail
                timerActive = false
                val correct = answeredCorrectly.count { it }
                val accuracy = if (questions.isEmpty()) 0f else correct.toFloat() / questions.size
                phase = if (accuracy >= boss.requiredAccuracy) BossPhase.VICTORY else BossPhase.DEFEAT
            }
        }
    }

    Box(
        modifier = modifier
            .fillMaxSize()
            .background(BgDeep)
    ) {
        StarfieldBackground(starCount = 80)

        when (phase) {
            BossPhase.INTRO -> {
                BossIntroContent(
                    boss = boss,
                    onBegin = {
                        phase = BossPhase.CHALLENGE
                        if (boss.timeLimitSeconds != null) timerActive = true
                    },
                    onBack = onBack
                )
            }

            BossPhase.CHALLENGE -> {
                if (currentIndex < questions.size) {
                    BossChallengeContent(
                        boss = boss,
                        question = questions[currentIndex],
                        questionNumber = currentIndex + 1,
                        totalQuestions = questions.size,
                        answersCorrect = answeredCorrectly.count { it },
                        selectedOption = selectedOption,
                        isRevealed = isAnswerRevealed,
                        remainingSeconds = if (boss.timeLimitSeconds != null) remainingSeconds else null,
                        onOptionSelected = { idx ->
                            if (!isAnswerRevealed) {
                                selectedOption = idx
                                isAnswerRevealed = true
                                answeredCorrectly.add(idx == questions[currentIndex].correctIndex)
                            }
                        },
                        onNext = {
                            val isLast = currentIndex + 1 >= questions.size
                            if (isLast) {
                                timerActive = false
                                val correct = answeredCorrectly.count { it }
                                val accuracy = correct.toFloat() / questions.size
                                phase = if (accuracy >= boss.requiredAccuracy) BossPhase.VICTORY else BossPhase.DEFEAT
                            } else {
                                currentIndex++
                                selectedOption = null
                                isAnswerRevealed = false
                            }
                        }
                    )
                }
            }

            BossPhase.VICTORY -> {
                VictoryContent(
                    boss = boss,
                    correctCount = answeredCorrectly.count { it },
                    totalCount = questions.size,
                    elapsedSeconds = boss.timeLimitSeconds?.minus(remainingSeconds),
                    onBack = onBack
                )
            }

            BossPhase.DEFEAT -> {
                DefeatContent(
                    boss = boss,
                    correctCount = answeredCorrectly.count { it },
                    totalCount = questions.size,
                    onRetry = {
                        currentIndex = 0
                        selectedOption = null
                        isAnswerRevealed = false
                        answeredCorrectly.clear()
                        remainingSeconds = boss.timeLimitSeconds ?: 0
                        phase = BossPhase.CHALLENGE
                        if (boss.timeLimitSeconds != null) timerActive = true
                    },
                    onBack = onBack
                )
            }
        }
    }
}

// ── Intro screen ──────────────────────────────────────────────────────────────

@Composable
private fun BossIntroContent(
    boss: BossChallenge,
    onBegin: () -> Unit,
    onBack: () -> Unit
) {
    val infiniteTransition = rememberInfiniteTransition(label = "bossGlow")
    val glow by infiniteTransition.animateFloat(
        initialValue = 0.7f,
        targetValue = 1.0f,
        animationSpec = infiniteRepeatable(
            animation = tween(1600, easing = FastOutSlowInEasing),
            repeatMode = RepeatMode.Reverse
        ),
        label = "glow"
    )

    Column(
        modifier = Modifier
            .fillMaxSize()
            .statusBarsPadding()
    ) {
        IconButton(
            onClick = onBack,
            modifier = Modifier.padding(8.dp)
        ) {
            Icon(
                imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                contentDescription = "Back",
                tint = Gold
            )
        }

        Column(
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center,
            modifier = Modifier
                .fillMaxSize()
                .padding(horizontal = 28.dp)
                .verticalScroll(rememberScrollState())
        ) {
            // Boss emblem
            Box(
                contentAlignment = Alignment.Center,
                modifier = Modifier
                    .size(120.dp)
                    .scale(glow)
                    .clip(CircleShape)
                    .background(
                        Brush.radialGradient(
                            colors = listOf(
                                Wrong.copy(alpha = 0.30f),
                                BgDeep
                            )
                        )
                    )
                    .border(2.dp, Wrong.copy(alpha = 0.70f), CircleShape)
            ) {
                Icon(
                    imageVector = Icons.Default.Shield,
                    contentDescription = null,
                    tint = Wrong,
                    modifier = Modifier.size(56.dp)
                )
            }

            Spacer(modifier = Modifier.height(28.dp))

            Box(
                modifier = Modifier
                    .clip(StellaeShapes.full)
                    .background(Wrong.copy(alpha = 0.12f))
                    .border(1.dp, Wrong.copy(alpha = 0.40f), StellaeShapes.full)
                    .padding(horizontal = 14.dp, vertical = 5.dp)
            ) {
                Text(
                    text = boss.title,
                    style = StellaeTypography.label.copy(color = Wrong)
                )
            }

            Spacer(modifier = Modifier.height(12.dp))

            Text(
                text = boss.name,
                style = StellaeTypography.displayMd.copy(
                    color = GoldBright,
                    fontWeight = FontWeight.Bold
                ),
                textAlign = TextAlign.Center
            )

            Spacer(modifier = Modifier.height(12.dp))

            Text(
                text = boss.description,
                style = StellaeTypography.bodyLg.copy(
                    color = TextSecondary,
                    lineHeight = 26.sp
                ),
                textAlign = TextAlign.Center
            )

            Spacer(modifier = Modifier.height(24.dp))

            // Challenge requirements
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .clip(StellaeShapes.lg)
                    .background(BgCard)
                    .border(1.dp, BorderGlow, StellaeShapes.lg)
                    .padding(16.dp),
                verticalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                Text(
                    text = "Challenge Requirements",
                    style = StellaeTypography.label.copy(color = TextMuted)
                )
                RequirementRow(label = "Questions", value = boss.questionCount.toString())
                RequirementRow(
                    label = "Required Accuracy",
                    value = "${(boss.requiredAccuracy * 100).toInt()}%"
                )
                if (boss.timeLimitSeconds != null) {
                    RequirementRow(
                        label = "Time Limit",
                        value = formatSeconds(boss.timeLimitSeconds)
                    )
                }
                RequirementRow(
                    label = "Minimum Rank",
                    value = boss.requiredRank.title
                )
            }

            Spacer(modifier = Modifier.height(32.dp))

            PrimaryButton(
                text = "Begin Challenge",
                onClick = onBegin,
                modifier = Modifier.fillMaxWidth()
            )
            Spacer(modifier = Modifier.height(12.dp))
            SecondaryButton(
                text = "Not Ready Yet",
                onClick = onBack,
                modifier = Modifier.fillMaxWidth()
            )

            Spacer(modifier = Modifier.height(32.dp))
        }
    }
}

// ── Challenge quiz ────────────────────────────────────────────────────────────

@Composable
private fun BossChallengeContent(
    boss: BossChallenge,
    question: BossQuestion,
    questionNumber: Int,
    totalQuestions: Int,
    answersCorrect: Int,
    selectedOption: Int?,
    isRevealed: Boolean,
    remainingSeconds: Int?,
    onOptionSelected: (Int) -> Unit,
    onNext: () -> Unit
) {
    val progressFraction = questionNumber.toFloat() / totalQuestions.toFloat()
    val progressAnim by animateFloatAsState(
        targetValue = progressFraction,
        animationSpec = tween(400),
        label = "progress"
    )

    val timerColor = when {
        remainingSeconds == null -> Gold
        remainingSeconds > 20    -> Gold
        remainingSeconds > 10    -> Color(0xFFFBBF24) // amber
        else                     -> Wrong
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .statusBarsPadding()
    ) {
        // Header with title, timer, progress
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .background(BgCard)
                .padding(horizontal = 16.dp, vertical = 12.dp)
        ) {
            Row(
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween,
                modifier = Modifier.fillMaxWidth()
            ) {
                Column {
                    Text(
                        text = boss.name,
                        style = StellaeTypography.bodySm.copy(color = Gold)
                    )
                    Text(
                        text = "$answersCorrect / $questionNumber-1 correct",
                        style = StellaeTypography.caption.copy(color = TextMuted)
                    )
                }
                if (remainingSeconds != null) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        modifier = Modifier
                            .clip(StellaeShapes.full)
                            .background(timerColor.copy(alpha = 0.12f))
                            .border(1.dp, timerColor.copy(alpha = 0.40f), StellaeShapes.full)
                            .padding(horizontal = 12.dp, vertical = 6.dp)
                    ) {
                        Icon(
                            imageVector = Icons.Default.Timer,
                            contentDescription = null,
                            tint = timerColor,
                            modifier = Modifier.size(14.dp)
                        )
                        Spacer(modifier = Modifier.width(4.dp))
                        Text(
                            text = formatSeconds(remainingSeconds),
                            style = StellaeTypography.bodyMd.copy(
                                color = timerColor,
                                fontWeight = FontWeight.Bold
                            )
                        )
                    }
                }
            }
            Spacer(modifier = Modifier.height(8.dp))
            // Progress bar
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(6.dp)
                    .clip(StellaeShapes.full)
                    .background(BgSurface)
            ) {
                Box(
                    modifier = Modifier
                        .fillMaxWidth(progressAnim)
                        .fillMaxHeight()
                        .clip(StellaeShapes.full)
                        .background(Wrong)
                )
            }
        }

        Column(
            modifier = Modifier
                .fillMaxSize()
                .verticalScroll(rememberScrollState())
                .padding(horizontal = 16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            Spacer(modifier = Modifier.height(12.dp))

            // Question number indicator
            Text(
                text = "Question $questionNumber of $totalQuestions",
                style = StellaeTypography.label.copy(color = TextMuted)
            )

            // Question
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .clip(StellaeShapes.xl)
                    .background(BgCard)
                    .border(1.dp, BorderGlow, StellaeShapes.xl)
                    .padding(20.dp)
            ) {
                Text(
                    text = question.text,
                    style = StellaeTypography.displaySm.copy(
                        color = TextPrimary,
                        fontWeight = FontWeight.Bold
                    ),
                    textAlign = TextAlign.Center,
                    modifier = Modifier.fillMaxWidth()
                )
            }

            // Options
            question.options.forEachIndexed { idx, option ->
                val state = when {
                    !isRevealed && selectedOption == idx -> QuizOptionState.DEFAULT
                    isRevealed && idx == question.correctIndex -> QuizOptionState.CORRECT
                    isRevealed && idx == selectedOption && idx != question.correctIndex -> QuizOptionState.WRONG
                    else -> QuizOptionState.DEFAULT
                }
                QuizOption(
                    letter = ('A' + idx).toString(),
                    text = option,
                    state = state,
                    onClick = { onOptionSelected(idx) },
                    modifier = Modifier.fillMaxWidth()
                )
            }

            // Explanation / next button
            AnimatedVisibility(
                visible = isRevealed,
                enter = fadeIn(tween(300)),
                exit = fadeOut()
            ) {
                Column(verticalArrangement = Arrangement.spacedBy(12.dp)) {
                    val isCorrect = selectedOption == question.correctIndex
                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .clip(StellaeShapes.md)
                            .background(if (isCorrect) Correct.copy(alpha = 0.10f) else Wrong.copy(alpha = 0.10f))
                            .border(
                                1.dp,
                                if (isCorrect) Correct.copy(alpha = 0.40f) else Wrong.copy(alpha = 0.40f),
                                StellaeShapes.md
                            )
                            .padding(14.dp)
                    ) {
                        Text(
                            text = if (isCorrect)
                                "Correct! ${question.options[question.correctIndex]}"
                            else
                                "The correct answer is: ${question.options[question.correctIndex]}",
                            style = StellaeTypography.bodyMd.copy(
                                color = if (isCorrect) Correct else Wrong
                            )
                        )
                    }
                    PrimaryButton(
                        text = if (questionNumber < totalQuestions) "Next Question" else "See Results",
                        onClick = onNext,
                        modifier = Modifier.fillMaxWidth()
                    )
                }
            }

            Spacer(modifier = Modifier.height(24.dp))
        }
    }
}

// ── Victory / Defeat ──────────────────────────────────────────────────────────

@Composable
private fun VictoryContent(
    boss: BossChallenge,
    correctCount: Int,
    totalCount: Int,
    elapsedSeconds: Int?,
    onBack: () -> Unit
) {
    val infiniteTransition = rememberInfiniteTransition(label = "victoryGlow")
    val shimmer by infiniteTransition.animateFloat(
        initialValue = 0.7f,
        targetValue = 1.0f,
        animationSpec = infiniteRepeatable(
            animation = tween(1200, easing = FastOutSlowInEasing),
            repeatMode = RepeatMode.Reverse
        ),
        label = "shimmer"
    )

    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center,
        modifier = Modifier
            .fillMaxSize()
            .statusBarsPadding()
            .padding(horizontal = 28.dp)
            .verticalScroll(rememberScrollState())
    ) {
        // Victory emblem
        Box(
            contentAlignment = Alignment.Center,
            modifier = Modifier
                .size(120.dp)
                .scale(shimmer)
                .clip(CircleShape)
                .background(
                    Brush.radialGradient(
                        colors = listOf(Gold.copy(alpha = 0.35f), BgDeep)
                    )
                )
                .border(2.dp, Gold, CircleShape)
        ) {
            Text(
                text = "\u2605",
                style = StellaeTypography.displayLg.copy(
                    color = Gold,
                    fontSize = 56.sp
                )
            )
        }

        Spacer(modifier = Modifier.height(24.dp))

        Text(
            text = "Victory!",
            style = StellaeTypography.displayLg.copy(
                color = GoldBright,
                fontWeight = FontWeight.Bold,
                fontSize = 48.sp
            ),
            textAlign = TextAlign.Center
        )

        Text(
            text = "You have defeated",
            style = StellaeTypography.bodyMd.copy(color = TextSecondary),
            textAlign = TextAlign.Center,
            modifier = Modifier.padding(top = 8.dp)
        )
        Text(
            text = boss.name,
            style = StellaeTypography.displaySm.copy(color = Gold),
            textAlign = TextAlign.Center
        )

        Spacer(modifier = Modifier.height(28.dp))

        Row(
            horizontalArrangement = Arrangement.spacedBy(12.dp),
            modifier = Modifier.fillMaxWidth()
        ) {
            StatTile(
                label = "Score",
                value = "$correctCount / $totalCount",
                color = Correct,
                modifier = Modifier.weight(1f)
            )
            val accuracyPct = if (totalCount > 0) (correctCount * 100 / totalCount) else 0
            StatTile(
                label = "Accuracy",
                value = "$accuracyPct%",
                color = Gold,
                modifier = Modifier.weight(1f)
            )
            if (elapsedSeconds != null) {
                StatTile(
                    label = "Time",
                    value = formatSeconds(elapsedSeconds),
                    color = TextPrimary,
                    modifier = Modifier.weight(1f)
                )
            }
        }

        Spacer(modifier = Modifier.height(32.dp))

        PrimaryButton(
            text = "Return",
            onClick = onBack,
            modifier = Modifier.fillMaxWidth()
        )
    }
}

@Composable
private fun DefeatContent(
    boss: BossChallenge,
    correctCount: Int,
    totalCount: Int,
    onRetry: () -> Unit,
    onBack: () -> Unit
) {
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center,
        modifier = Modifier
            .fillMaxSize()
            .statusBarsPadding()
            .padding(horizontal = 28.dp)
            .verticalScroll(rememberScrollState())
    ) {
        Box(
            contentAlignment = Alignment.Center,
            modifier = Modifier
                .size(110.dp)
                .clip(CircleShape)
                .background(Wrong.copy(alpha = 0.15f))
                .border(2.dp, Wrong.copy(alpha = 0.60f), CircleShape)
        ) {
            Text(
                text = "\u2715",
                style = StellaeTypography.displayLg.copy(
                    color = Wrong,
                    fontSize = 48.sp
                )
            )
        }

        Spacer(modifier = Modifier.height(24.dp))

        Text(
            text = "Defeated",
            style = StellaeTypography.displayLg.copy(
                color = Wrong,
                fontWeight = FontWeight.Bold,
                fontSize = 42.sp
            ),
            textAlign = TextAlign.Center
        )

        Text(
            text = "${boss.name} has prevailed",
            style = StellaeTypography.bodyLg.copy(color = TextSecondary),
            textAlign = TextAlign.Center,
            modifier = Modifier.padding(top = 8.dp, bottom = 20.dp)
        )

        val requiredPct = (boss.requiredAccuracy * 100).toInt()
        val actualPct = if (totalCount > 0) (correctCount * 100 / totalCount) else 0

        Box(
            modifier = Modifier
                .fillMaxWidth()
                .clip(StellaeShapes.md)
                .background(BgCard)
                .border(1.dp, BorderSubtle, StellaeShapes.md)
                .padding(14.dp)
        ) {
            Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                Text(
                    text = "Required: $requiredPct% accuracy",
                    style = StellaeTypography.bodyMd.copy(color = TextSecondary)
                )
                Text(
                    text = "Your result: $actualPct% ($correctCount / $totalCount correct)",
                    style = StellaeTypography.bodyMd.copy(color = Wrong)
                )
                Spacer(modifier = Modifier.height(4.dp))
                XpProgressBar(
                    progress = actualPct.toFloat() / 100f,
                    modifier = Modifier.fillMaxWidth()
                )
            }
        }

        Spacer(modifier = Modifier.height(32.dp))

        PrimaryButton(
            text = "Try Again",
            onClick = onRetry,
            modifier = Modifier.fillMaxWidth()
        )
        Spacer(modifier = Modifier.height(12.dp))
        SecondaryButton(
            text = "Retreat",
            onClick = onBack,
            modifier = Modifier.fillMaxWidth()
        )
    }
}

// ── Helper composables ────────────────────────────────────────────────────────

@Composable
private fun RequirementRow(label: String, value: String) {
    Row(
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween,
        modifier = Modifier.fillMaxWidth()
    ) {
        Text(
            text = label,
            style = StellaeTypography.bodyMd.copy(color = TextSecondary)
        )
        Text(
            text = value,
            style = StellaeTypography.bodyMd.copy(
                color = Gold,
                fontWeight = FontWeight.Bold
            )
        )
    }
}

@Composable
private fun StatTile(
    label: String,
    value: String,
    color: Color,
    modifier: Modifier = Modifier
) {
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = modifier
            .clip(StellaeShapes.md)
            .background(BgCard)
            .border(1.dp, BorderSubtle, StellaeShapes.md)
            .padding(vertical = 16.dp, horizontal = 8.dp)
    ) {
        Text(
            text = value,
            style = StellaeTypography.displaySm.copy(
                color = color,
                fontWeight = FontWeight.Bold
            ),
            textAlign = TextAlign.Center
        )
        Text(
            text = label,
            style = StellaeTypography.caption.copy(color = TextMuted),
            textAlign = TextAlign.Center
        )
    }
}

// ── Utility ───────────────────────────────────────────────────────────────────

private fun formatSeconds(seconds: Int): String {
    val m = seconds / 60
    val s = seconds % 60
    return if (m > 0) "${m}m ${"%02d".format(s)}s" else "${s}s"
}

private val BgSurface = Color(0xFF232A45)
